# Generated by Django 2.2.7 on 2019-11-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='user',
        ),
    ]
