# Generated by Django 2.2.7 on 2019-11-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20191126_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='balance',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='balance',
            new_name='acoount',
        ),
    ]
