# Generated by Django 2.2.7 on 2019-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20191126_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_expense_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
