# Generated by Django 2.2.7 on 2019-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_auto_20191126_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_expense_amount',
        ),
    ]
