# Generated by Django 2.2.7 on 2019-11-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_auto_20191128_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='spending',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
