# Generated by Django 2.2.7 on 2019-11-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0018_auto_20191129_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetracker',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
