# Generated by Django 2.2.7 on 2019-11-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0019_auto_20191129_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetracker',
            name='slug',
        ),
    ]
