# Generated by Django 2.2.7 on 2019-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0021_balancetracker_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancetracker',
            name='identifier',
        ),
        migrations.AddField(
            model_name='balancetracker',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='spending',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
