# Generated by Django 2.2.7 on 2019-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0022_auto_20191129_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='info',
            field=models.CharField(blank=True, default='income', max_length=10),
        ),
        migrations.AddField(
            model_name='spending',
            name='info',
            field=models.CharField(blank=True, default='spending', max_length=10),
        ),
    ]
