# Generated by Django 2.2.7 on 2019-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0023_auto_20191129_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='info',
            field=models.CharField(blank=True, default='Income', max_length=10),
        ),
        migrations.AlterField(
            model_name='spending',
            name='info',
            field=models.CharField(blank=True, default='Spending', max_length=10),
        ),
    ]
