# Generated by Django 2.2.7 on 2020-02-05 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0027_auto_20200120_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetracker',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
